#!/usr/bin/env bash
# ─── PeerCast — Native (bare-metal) setup for Linux ────────────────────────
# Installs PeerCast directly on a Raspberry Pi or Linux laptop WITHOUT Docker.
# Installs Node.js, builds the project, configures .env, and registers a
# systemd service so it auto-starts on boot.
#
# Usage:
#   Download this script, inspect it, then run: bash setup-native.sh
#   — or (needs sudo) — sudo bash setup-native.sh
#
# Tested on: Raspberry Pi OS (32/64-bit), Ubuntu 20.04+, Debian 10+

set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()  { printf "${CYAN}[info]${NC}  %s\n" "$*"; }
ok()    { printf "${GREEN}[  ok]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[warn]${NC}  %s\n" "$*"; }
err()   { printf "${RED}[error]${NC} %s\n" "$*" >&2; exit 1; }

# ── Check root ─────────────────────────────────────────────────────────────
# We don't REQUIRE root (can install as user + user systemd), but most will
# run this as root via curl|sh. Detect and adapt.
if [ "$(id -u)" -eq 0 ]; then
  RUN_USER="${SUDO_USER:-root}"
  SUDO=""
  RUN_HOME="/home/${RUN_USER}"
  [ "${RUN_USER}" = "root" ] && RUN_HOME="/root"
  warn "Running as root — installing for user '${RUN_USER}'."
else
  RUN_USER="$(whoami)"
  SUDO="sudo"
  RUN_HOME="${HOME}"
fi

# ── Usage / preflight ──────────────────────────────────────────────────────
REPO_URL="https://github.com/luciVuc/peer-cast.git"
REPO_REF="72b4f7a2f986c7ff155ce1ed2333ae7f040174cf"
INSTALL_DIR="${RUN_HOME}/peer-cast"

command -v openssl >/dev/null 2>&1 || err "openssl is required. Install: ${SUDO} apt install openssl"

# ── Install Node.js (if missing) ───────────────────────────────────────────
install_node() {
  if command -v node >/dev/null 2>&1; then
    NODE_VER="$(node -v)"
    NODE_MAJOR="$(node -v | sed 's/v\([0-9]*\).*/\1/')"
    if [ "${NODE_MAJOR}" -ge 20 ]; then
      ok "Node.js ${NODE_VER} already installed (>= 20)."
      return
    fi
    warn "Node.js ${NODE_VER} is too old (need >= 20). Installing 22 LTS..."
  else
    info "Node.js not found — installing Node 22 LTS."
  fi

  if command -v apt-get >/dev/null 2>&1; then
    # Debian/Ubuntu/Raspberry Pi OS — use NodeSource
    info "Installing the distribution Node.js package..."
    $SUDO apt-get update
    $SUDO apt-get install -y nodejs npm build-essential python3 make g++
  elif command -v dnf >/dev/null 2>&1; then
    info "Installing via dnf..."
    $SUDO dnf install -y nodejs npm make gcc-c++ python3
  elif command -v apk >/dev/null 2>&1; then
    info "Installing via apk..."
    $SUDO apk add --no-cache nodejs npm python3 make g++
  else
    err "Unsupported package manager. Install Node.js 20+ manually then re-run."
  fi

  command -v node >/dev/null 2>&1 || err "Node.js installation failed."
  ok "Node.js $(node -v) installed."
}

# ── Clone the repo ─────────────────────────────────────────────────────────
clone_repo() {
  if [ -d "${INSTALL_DIR}/.git" ]; then
    info "Repo already at ${INSTALL_DIR} — pulling latest..."
    git -C "${INSTALL_DIR}" pull --ff-only || warn "git pull failed; continuing with existing code."
  else
    info "Cloning PeerCast → ${INSTALL_DIR} ..."
    ${SUDO} git clone "${REPO_URL}" "${INSTALL_DIR}" 2>/dev/null \
      || git clone "${REPO_URL}" "${INSTALL_DIR}"
    git -C "${INSTALL_DIR}" checkout --detach "${REPO_REF}"
  fi
  # Ensure ownership
  ${SUDO} chown -R "${RUN_USER}":"${RUN_USER}" "${INSTALL_DIR}" 2>/dev/null || true
  cd "${INSTALL_DIR}"
}

# ── Interactive prompts ───────────────────────────────────────────────────
ask_domain() {
  echo ""
  printf "${BOLD}─── PeerCast Native Setup ───${NC}\n"
  echo ""
  read -rp "$(printf "${CYAN}Domain or public IP for this server:${NC} [e.g. peercast.example.com or 1.2.3.4] ")" DOMAIN
  DOMAIN="${DOMAIN:-localhost}"
  read -rp "$(printf "${CYAN}Admin username (the handle you'll register):${NC} ")" ADMIN
  ADMIN="${ADMIN:-admin}"
  read -rp "$(printf "${CYAN}Configure email (SMTP)?${NC} [y/N] ")" SMTP_CHOICE
  SMTP_CHOICE="${SMTP_CHOICE:-N}"
}

# ── Write .env ─────────────────────────────────────────────────────────────
write_env() {
  JWT_SECRET="$(openssl rand -hex 32)"
  ADMIN_BOOTSTRAP_SECRET="$(openssl rand -hex 32)"
  if [ -f .env ] && grep -q '^JWT_SECRET=' .env; then
    JWT_SECRET="$(grep '^JWT_SECRET=' .env | cut -d= -f2-)"
  fi
  if [ -f .env ] && grep -q '^ADMIN_BOOTSTRAP_SECRET=' .env; then
    ADMIN_BOOTSTRAP_SECRET="$(grep '^ADMIN_BOOTSTRAP_SECRET=' .env | cut -d= -f2-)"
  fi
  cat > .env <<EOF
# PeerCast environment — generated by setup-native.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

PORT=8787
HOST=0.0.0.0
NODE_ENV=production
PUBLIC_HOST=${DOMAIN}
PUBLIC_SECURE=true
JWT_SECRET=${JWT_SECRET}
DATABASE_FILE=./data/peercast.db
ADMIN_USERNAMES=${ADMIN}
ADMIN_BOOTSTRAP_SECRET=${ADMIN_BOOTSTRAP_SECRET}
REGISTRATION_MODE=open
REQUIRE_EMAIL_VERIFICATION=false
APP_URL=https://${DOMAIN}
APP_NAME=PeerCast
CORS_ORIGINS=*
EOF
printf "${BOLD}Admin bootstrap secret (keep private; required when registering @%s):${NC}\n%s\n" "${ADMIN}" "$(grep '^ADMIN_BOOTSTRAP_SECRET=' .env | cut -d= -f2-)"
  chmod 600 .env
  ok ".env written (JWT_SECRET generated)."
}

# ── SMTP (optional) ────────────────────────────────────────────────────────
smtp_setup() {
  if [ "${SMTP_CHOICE}" = "y" ] || [ "${SMTP_CHOICE}" = "Y" ]; then
    echo ""
    info "Enter your SMTP details (press Enter to skip any field):"
    read -rp "  SMTP host [smtp.resend.com]: " SMTP_HOST; SMTP_HOST="${SMTP_HOST:-smtp.resend.com}"
    read -rp "  SMTP port [587]: " SMTP_PORT; SMTP_PORT="${SMTP_PORT:-587}"
    read -rp "  SMTP user [resend]: " SMTP_USER; SMTP_USER="${SMTP_USER:-resend}"
    read -rp "  SMTP password / API key: " SMTP_PASS
    read -rp "  SMTP from [PeerCast <noreply@${DOMAIN}>]: " SMTP_FROM
    SMTP_FROM="${SMTP_FROM:-PeerCast <noreply@${DOMAIN}>}"

    cat >> .env <<EOF

# Email
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_SECURE=false
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM}
EOF
    ok "SMTP configured."
  else
    echo ""
    warn "Email skipped — verification links will be printed to the server log."
    warn "Add SMTP settings to .env later and restart."
  fi
}

# ── Install & build ────────────────────────────────────────────────────────
build_project() {
  info "Installing npm dependencies (this may take a few minutes on a Pi)..."
  as_user() { if [ "$(id -u)" -eq 0 ]; then su "${RUN_USER}" -c "$*"; else bash -c "$*"; fi; }
  as_user "cd ${INSTALL_DIR} && npm ci 2>/dev/null || npm install"
  as_user "cd ${INSTALL_DIR} && npm run build"
  ok "Build complete."
}

# ── Install as systemd service ─────────────────────────────────────────────
install_service() {
  info "Registering systemd service peercast.service..."
  cat > /tmp/peercast.service <<EOF
[Unit]
Description=PeerCast — P2P broadcasting platform
After=network.target

[Service]
Type=simple
User=${RUN_USER}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
Environment=NODE_ENV=production
ExecStart=/usr/bin/node ${INSTALL_DIR}/packages/server/dist/index.js
Restart=on-failure
RestartSec=5
# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=false
ReadWritePaths=${INSTALL_DIR}/data
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  ${SUDO} mv /tmp/peercast.service /etc/systemd/system/peercast.service
  ${SUDO} systemctl daemon-reload
  ${SUDO} systemctl enable peercast
  ${SUDO} systemctl start peercast
  ok "Service installed and started. Enabled on boot."
}

# ── Main ──────────────────────────────────────────────────────────────────
install_node
clone_repo
ask_domain
write_env
smtp_setup
build_project
mkdir -p data
install_service

echo ""
printf "${GREEN}${BOLD}══════════════════════════════════════════════════════════════${NC}\n"
printf "${GREEN}${BOLD}  PeerCast is running natively!${NC}\n"
printf "${GREEN}${BOLD}══════════════════════════════════════════════════════════════${NC}\n"
echo ""
echo "  URL:        https://${DOMAIN}"
echo "  API:        https://${DOMAIN}/api/health"
echo "  Signaling:  https://${DOMAIN}/peerjs"
echo ""
echo "  Next steps:"
echo "    1. Open https://${DOMAIN}/register"
echo "    2. Register the '${ADMIN}' account (auto-promoted to admin)"
echo "    3. Start broadcasting!"
echo ""
echo "  Useful commands:"
echo "    systemctl status peercast        # check status"
echo "    journalctl -u peercast -f        # follow logs"
echo "    sudo systemctl restart peercast  # restart after .env change"
echo "    sudo systemctl stop peercast     # stop"
echo ""
if [ "${SMTP_CHOICE}" != "y" ] && [ "${SMTP_CHOICE}" != "Y" ]; then
  echo "  (Email not configured — verification links appear in the logs:)"
  echo "    journalctl -u peercast | grep verify-email"
  echo ""
fi
echo "  Project:  ${INSTALL_DIR}"
echo "  Config:   ${INSTALL_DIR}/.env"
echo ""
