#!/usr/bin/env bash
# ─── PeerCast — One-command Docker setup ───────────────────────────────────
# Detects Docker/Podman, generates secrets, creates .env, and starts the stack.
#
# Usage (pick one):
#   git clone https://github.com/luciVuc/peer-cast.git && cd peer-cast && bash setup.sh
#   Download this script, inspect it, then run: bash setup.sh
#
# Interactive prompts:
#   1. Your public domain or IP  (required)
#   2. Admin username            (the handle you'll register as admin)
#   3. Enable TURN relay?       (for symmetric-NAT viewers)
#   4. SMTP settings            (optional, for email verification)

set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()  { printf "${CYAN}[info]${NC}  %s\n" "$*"; }
ok()    { printf "${GREEN}[  ok]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[warn]${NC}  %s\n" "$*"; }
err()   { printf "${RED}[error]${NC} %s\n" "$*" >&2; exit 1; }

# ── Locate or clone the repo ──────────────────────────────────────────────
REPO_URL="https://github.com/luciVuc/peer-cast.git"
REPO_REF="9ed4ebde104dc5311c5c312f8c20f9f3960654bd"

# If we're already inside a peer-cast repo, use it.
if [ -f "packages/server/package.json" ] 2>/dev/null; then
  WORKDIR="$(pwd)"
elif [ -d ".git" ] && [ -f "package.json" ]; then
  # Might be the repo root but without the packages dir — could be a fresh clone
  WORKDIR="$(pwd)"
else
  # Curl-piped or run from outside the repo — clone into a temp dir
  WORKDIR="$(mktemp -d)/peer-cast"
  info "Cloning PeerCast into ${WORKDIR} ..."
  git clone --depth 1 "${REPO_URL}" "${WORKDIR}"
  git -C "${WORKDIR}" checkout --detach "${REPO_REF}"
fi
cd "${WORKDIR}"

# ── Preflight ──────────────────────────────────────────────────────────────
command -v openssl >/dev/null 2>&1 || err "openssl is required but not found. Install it first."
command -v docker >/dev/null 2>&1 || command -v podman >/dev/null 2>&1 || \
  err "Neither docker nor podman found. Install Docker: https://docs.docker.com/get-docker/"

# Detect compose command
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
elif podman compose version >/dev/null 2>&1; then
  COMPOSE="podman compose"
else
  err "No docker compose / podman compose found."
fi
info "Using: ${BOLD}${COMPOSE}${NC}"

# ── Interactive prompts ───────────────────────────────────────────────────
echo ""
printf "${BOLD}─── PeerCast Setup ───${NC}\n"
echo ""

# 1) Domain / IP
read -rp "$(printf "${CYAN}Domain or public IP for this server:${NC} [e.g. peercast.example.com or 1.2.3.4] ")" DOMAIN
DOMAIN="${DOMAIN:-localhost}"

# 2) Admin username
read -rp "$(printf "${CYAN}Admin username (the handle you'll register):${NC} ")" ADMIN
ADMIN="${ADMIN:-admin}"

# 3) TURN relay
read -rp "$(printf "${CYAN}Enable TURN relay for symmetric-NAT viewers?${NC} [y/N] ")" TURN_CHOICE
TURN_CHOICE="${TURN_CHOICE:-N}"

# 4) SMTP (optional)
read -rp "$(printf "${CYAN}Configure email (SMTP) now?${NC} [y/N] ")" SMTP_CHOICE
SMTP_CHOICE="${SMTP_CHOICE:-N}"

# ── Write .env ─────────────────────────────────────────────────────────────
JWT_SECRET_VAL="$(openssl rand -hex 32)"
ADMIN_BOOTSTRAP_SECRET_VAL="$(openssl rand -hex 32)"
# Preserve existing JWT_SECRET if upgrading
if [ -f .env ] && grep -q '^JWT_SECRET=' .env; then
  JWT_SECRET_VAL="$(grep '^JWT_SECRET=' .env | cut -d= -f2-)"
fi
if [ -f .env ] && grep -q '^ADMIN_BOOTSTRAP_SECRET=' .env; then
  ADMIN_BOOTSTRAP_SECRET_VAL="$(grep '^ADMIN_BOOTSTRAP_SECRET=' .env | cut -d= -f2-)"
fi

cat > .env <<EOF
# PeerCast environment — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

PORT=8787
HOST=0.0.0.0
NODE_ENV=production
PUBLIC_HOST=${DOMAIN}
PUBLIC_SECURE=true
JWT_SECRET=${JWT_SECRET_VAL}
DATABASE_FILE=/data/peercast.db
ADMIN_USERNAMES=${ADMIN}
ADMIN_BOOTSTRAP_SECRET=${ADMIN_BOOTSTRAP_SECRET_VAL}
REGISTRATION_MODE=open
REQUIRE_EMAIL_VERIFICATION=false
APP_URL=https://${DOMAIN}
APP_NAME=PeerCast
CORS_ORIGINS=*
EOF
printf "${BOLD}Admin bootstrap secret (keep private; required when registering @%s):${NC}\n%s\n" "${ADMIN}" "$(grep '^ADMIN_BOOTSTRAP_SECRET=' .env | cut -d= -f2-)"

if [ "${SMTP_CHOICE}" = "y" ] || [ "${SMTP_CHOICE}" = "Y" ]; then
  echo ""
  info "Enter your SMTP details (press Enter to skip any field):"
  read -rp "  SMTP host [smtp.resend.com]: " SMTP_HOST; SMTP_HOST="${SMTP_HOST:-smtp.resend.com}"
  read -rp "  SMTP port [587]: " SMTP_PORT; SMTP_PORT="${SMTP_PORT:-587}"
  read -rp "  SMTP user [resend]: " SMTP_USER; SMTP_USER="${SMTP_USER:-resend}"
  read -rp "  SMTP password / API key: " SMTP_PASS
  read -rp "  SMTP from [PeerCast <noreply@${DOMAIN}>]: " SMTP_FROM
  SMTP_FROM="${SMTP_FROM:-PeerCast <noreply@${DOMAIN}>}"

  cat >> .env <<EOF

# Email
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_SECURE=false
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM}
EOF
  ok "SMTP configured."
else
  echo ""
  warn "Email skipped — verification links will be printed to the server log."
  warn "You can add SMTP settings to .env later."
fi

ok ".env written."

# ── TURN relay config ─────────────────────────────────────────────────────
TURN_PROFILE=""
if [ "${TURN_CHOICE}" = "y" ] || [ "${TURN_CHOICE}" = "Y" ]; then
  TURN_PROFILE="--profile turn"
  PUBLIC_IP="${DOMAIN}"
  if [[ ! "${DOMAIN}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    PUBLIC_IP="$(dig +short "${DOMAIN}" | head -1 || true)"
    if [ -z "${PUBLIC_IP}" ]; then
      PUBLIC_IP="${DOMAIN}"
      warn "Could not resolve ${DOMAIN} — set external-ip in turn/turnserver.conf manually."
    fi
  fi

  TURN_USER="peercast"
  TURN_PASS="$(openssl rand -hex 16)"
  read -rp "$(printf "${CYAN}TURN username:${NC} [${TURN_USER}] ")" INPUT_TURN_USER; TURN_USER="${INPUT_TURN_USER:-${TURN_USER}}"
  read -rp "$(printf "${CYAN}TURN password:${NC} [auto-generated] ")" INPUT_TURN_PASS; TURN_PASS="${INPUT_TURN_PASS:-${TURN_PASS}}"

  # Update turnserver.conf (portable: works on both GNU and BSD sed)
  if sed --version >/dev/null 2>&1; then
    sed -i \
      -e "s/^#external-ip=.*/external-ip=${PUBLIC_IP}/" \
      -e "s/^#user=.*/user=${TURN_USER}:${TURN_PASS}/" \
      turn/turnserver.conf
  else
    sed -i '' \
      -e "s/^#external-ip=.*/external-ip=${PUBLIC_IP}/" \
      -e "s/^#user=.*/user=${TURN_USER}:${TURN_PASS}/" \
      turn/turnserver.conf
  fi

  cat >> .env <<EOF

# TURN relay
ICE_SERVERS=[{"urls":"stun:stun.l.google.com:19302"},{"urls":"turn:${DOMAIN}:3478","username":"${TURN_USER}","credential":"${TURN_PASS}"}]
EOF
  ok "TURN configured. Credentials written to turn/turnserver.conf and .env."
  warn "Open UDP 3478 + 49160-49200 on your firewall for the TURN relay."
fi

# ── Start the stack ────────────────────────────────────────────────────────
echo ""
info "Building and starting PeerCast..."
${COMPOSE} up -d --build ${TURN_PROFILE}

echo ""
printf "${GREEN}${BOLD}══════════════════════════════════════════════════════════════${NC}\n"
printf "${GREEN}${BOLD}  PeerCast is running!${NC}\n"
printf "${GREEN}${BOLD}══════════════════════════════════════════════════════════════${NC}\n"
echo ""
echo "  URL:        https://${DOMAIN}"
echo "  API:        https://${DOMAIN}/api/health"
echo "  Signaling:  https://${DOMAIN}/peerjs"
echo ""
echo "  Next steps:"
echo "    1. Open https://${DOMAIN}/register"
echo "    2. Register the '${ADMIN}' account (auto-promoted to admin)"
echo "    3. Start broadcasting!"
echo ""
if [ "${SMTP_CHOICE}" != "y" ] && [ "${SMTP_CHOICE}" != "Y" ]; then
  echo "  (Email is not configured — verification links appear in the server log)"
  echo "    View logs:  ${COMPOSE} logs -f peercast"
fi
echo ""
echo "  Useful commands:"
echo "    ${COMPOSE} logs -f peercast      # follow logs"
echo "    ${COMPOSE} restart peercast      # restart after config change"
echo "    ${COMPOSE} down                   # stop"
echo "    ${COMPOSE} --profile turn up -d   # start with TURN relay"
echo ""
